"""Analysis placeholders for metrics, statistics, and plotting."""

from .metrics import (
    aggregate_casualties_by_unit,
    InferenceTimingSummary,
    MockWhiteCellMetricHook,
    action_entropy,
    combat_turn_count,
    doctrine_compliance_rate,
    escalation_index,
    escalation_sensitivity_index,
    inference_time_summary,
    json_parsing_success_rate,
    load_jsonl_records,
    mean_remaining_force_ratio,
    tactical_risk_score,
    tactical_rationality_score,
    tactic_transition_frequency,
    win_rate,
)
from .plots import (
    PlotBundle,
    VisualizationBundle,
    build_aggregate_visualizations,
    build_battlefield_replay,
    build_experiment_plots,
    plot_parsing_success_by_agent,
)
from .stats import SummaryStatistics, summarize_runs

__all__ = [
    "InferenceTimingSummary",
    "MockWhiteCellMetricHook",
    "PlotBundle",
    "SummaryStatistics",
    "VisualizationBundle",
    "aggregate_casualties_by_unit",
    "action_entropy",
    "build_aggregate_visualizations",
    "build_battlefield_replay",
    "build_experiment_plots",
    "combat_turn_count",
    "doctrine_compliance_rate",
    "escalation_index",
    "escalation_sensitivity_index",
    "inference_time_summary",
    "json_parsing_success_rate",
    "load_jsonl_records",
    "mean_remaining_force_ratio",
    "plot_parsing_success_by_agent",
    "tactical_risk_score",
    "summarize_runs",
    "tactical_rationality_score",
    "tactic_transition_frequency",
    "win_rate",
]
